package com.example.fixnow.ui.theme

import androidx.compose.ui.graphics.Color

val OrangePrimary    = Color(0xFFFFB300)
val OrangeLight      = Color(0xFFFFD54F)
val OrangeDark       = Color(0xFFCC8E00)
val YellowHeader     = Color(0xFFFBC02D)
val YellowHeaderEnd  = Color(0xFFFFF176)
val BackgroundWhite  = Color(0xFFFAFAFA)
val BackgroundCard   = Color(0xFFFFFFFF)
val BackgroundLight  = Color(0xFFFDFDFD)
val TextPrimary      = Color(0xFF333333)
val TextSecondary    = Color(0xFF757575)
val TextOnOrange     = Color(0xFFFFFFFF)
val TextGray         = Color(0xFF9E9E9E)
val ColorSuccess     = Color(0xFF4CAF50)
val ColorError       = Color(0xFFE53935)
val ColorNavUnselected = Color(0xFF9E9E9E)
val CyanAccent       = Color(0xFF00BCD4)
val OrangeSecondary  = Color(0xFFFF8F00)
val BackgroundDark   = Color(0xFF121212)
val SurfaceLight     = Color(0xFFFFFFFF)
val SurfaceDark      = Color(0xFF1E1E1E)
val TextBlack        = Color(0xFF212121)
val TextWhite        = Color(0xFFF5F5F5)
val ErrorRed         = Color(0xFFCF6679)
